---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Install Apache2
  apt:
    name: apache2
    state: present
  notify: Restart Apache
